Repository teamCampro/campro_FE, pull requests merged in 2024-01, with the labels that each got.

#5 [#3] feat: pagination 구현
  .eslintrc.json
  public/data/onboardingMockData.json
  public/svgs/ArrowLeft.svg
  public/svgs/ArrowLeftGray.svg
  src/app/(afterLogin)/onboarding/_components/OnBoardingItem.tsx
  src/app/(afterLogin)/onboarding/_components/OnboardingList.tsx
  src/app/(afterLogin)/onboarding/page.tsx
  src/app/(beforeLogin)/page.tsx
  src/app/_components/Pagination.tsx
  src/app/_components/index.ts
  src/app/_hooks/usePagination.ts
  src/svg.d.ts
Labels: 🚀 기능 구현

#8 [#4] feat: 온보딩 페이지 레이아웃 구현
  public/png/onbording-1920.png
  public/png/tent.gif
  public/svgs/calendar.svg
  public/svgs/comming.svg
  public/svgs/glamping.svg
  public/svgs/index.ts
  public/svgs/like.svg
  public/svgs/location.svg
  public/svgs/minus.svg
  public/svgs/people.svg
  public/svgs/plus.svg
  public/svgs/search.svg
  public/svgs/tent.svg
  src/app/(afterLogin)/.gitkeep
  src/app/(afterLogin)/onboarding/_components/OnBoardingItem.tsx
  src/app/(afterLogin)/onboarding/_components/OnboardingList.tsx
  src/app/(afterLogin)/onboarding/page.tsx
  src/app/(beforeLogin)/page.tsx
  src/app/(header&footer)/.gitkeep
  src/app/(header&footer)/layout.tsx
  src/app/(header&footer)/page.tsx
  src/app/(header)/.gitkeep
  src/app/(onboarding)/_components/OnBoardingItem.tsx
  src/app/(onboarding)/_components/OnboardingList.tsx
  src/app/(onboarding)/onboard/layout.tsx
  src/app/(onboarding)/onboard/page.tsx
  src/app/(onboarding)/onboard/question/page.tsx
  src/app/_components/Button/index.tsx
  src/app/_components/Header/index.tsx
  src/app/_components/Pagination.tsx
  src/app/_components/index.ts
  src/app/globals.css
  src/svg.d.ts
  tailwind.config.ts
  tsconfig.json
Labels: 🚀 기능 구현

#14 [#12] feat: 공통 헤더, onboarding header, footer 컴포넌트, svg, 공통폰트
  public/svgs/.gitkeep
  public/svgs/arrowLeft-normal.svg
  public/svgs/arrowRight-normal.svg
  public/svgs/index.ts
  src/app/(header&footer)/layout.tsx
  src/app/(onboarding)/_components/OnBoardingItem.tsx
  src/app/(onboarding)/_components/OnboardingHeader.tsx
  src/app/(onboarding)/onboard/layout.tsx
  src/app/(onboarding)/onboard/page.tsx
  src/app/_components/Button/CircleButton.tsx
  src/app/_components/Button/RoundButton.tsx
  src/app/_components/Button/index.tsx
  src/app/_components/Footer/index.tsx
  src/app/_components/Header/index.tsx
  src/app/_components/index.ts
  src/app/_types/index.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#15 [#13] feat: 메인페이지 검색바 UI 구현 및 리액트훅폼으로 공통 폼 및 인풋 컴포넌트 구현
  src/app/_components/Form/CommonForm.tsx
  src/app/_components/Input/CommonInput.tsx
  src/app/_components/Input/DateInput.tsx
  src/app/_components/Input/GroupCountInput.tsx
  src/app/_components/Input/LocationInput.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_components/index.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#21 [#20] : fix: global.css 린트 오류 해결
  src/app/globals.css
Labels: 🐞 버그

#17 [#10] feat: 카테고리, 칩 컴포넌트 구현
  package-lock.json
  package.json
  src/app/(onboarding)/_components/OnboardingHeader.tsx
  src/app/_components/CategoryItem.tsx
  src/app/_components/CategoryList.tsx
  src/app/_components/Chip.tsx
  src/app/_components/Input/DateInput.tsx
  src/app/_components/Input/GroupCountInput.tsx
  src/app/_components/Input/LocationInput.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_components/index.ts
  src/app/_constants/index.ts
  src/app/_constants/links.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#19 [#18] fix: onboarding 리스트 선택하고 뒤로 갈 시 전에 선택한 버튼 활성화 유지되게 수정
  src/app/(onboarding)/_components/OnBoardingItem.tsx
  src/app/(onboarding)/_components/OnboardingHeader.tsx
  src/app/(onboarding)/_components/OnboardingList.tsx
  src/app/(onboarding)/onboard/page.tsx
  src/app/(onboarding)/onboard/question/page.tsx
  src/app/_components/Button/index.tsx
  src/app/_components/Header/index.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#23 [#11] feat: 캠핑장 리스트 컴포넌트 구현
  public/data/campPlaceMockData.json
  public/svgs/arrowRight.svg
  public/svgs/coloredHeart.svg
  public/svgs/heart.svg
  public/svgs/index.ts
  public/svgs/right.svg
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/_components/CampPlaceList.tsx
  src/app/(header&footer)/_components/CampPlaceSection.tsx
  src/app/(header&footer)/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: 🚀 기능 구현

#28 [#27] fix: question 타입 오타 수정
  public/avifs/onbording.avif
  public/gifs/tent.gif
  public/png/onbording-1920.png
  public/png/tent.gif
  src/app/(onboarding)/_components/OnBoardingItem.tsx
  src/app/(onboarding)/_components/OnboardingList.tsx
  src/app/(onboarding)/onboard/question/page.tsx
  tailwind.config.ts
Labels: 🐞 버그

#16 feat: 배경이미지(취향 등록하기 버튼 섹션)
  public/avifs/hero.avif
  src/app/(header&footer)/page.tsx
  src/app/(onboarding)/_components/OnboardingItem.tsx
  src/app/(onboarding)/_components/OnboardingList.tsx
  src/app/(onboarding)/onboard/page.tsx
  src/app/_components/Button/index.tsx
  src/app/_components/Form/CommonForm.tsx
  src/app/_components/Hero/index.tsx
  src/app/_components/Input/CommonInput.tsx
  src/app/_components/index.ts
Labels: 🚀 기능 구현

#26 [#22] feat: react-datePicker 반응형 구현
  package-lock.json
  package.json
  public/svgs/arrowLeft-non.svg
  public/svgs/arrowRight-non.svg
  public/svgs/index.ts
  src/app/(header&footer)/page.tsx
  src/app/_components/Button/RoundButton.tsx
  src/app/_components/Controller/DatePickerController.tsx
  src/app/_components/Controller/LocationController.tsx
  src/app/_components/Dropdown/index.tsx
  src/app/_components/Form/CommonForm.tsx
  src/app/_components/Input/CommonInput.tsx
  src/app/_components/Input/DateInput.tsx
  src/app/_components/Input/DateInputView.tsx
  src/app/_components/Input/GroupCountInput.tsx
  src/app/_components/Input/LocationInput.tsx
  src/app/_components/Input/LocationInputView.tsx
  src/app/_components/Modal/ModalFooter.tsx
  src/app/_components/Modal/ModalForMobile.tsx
  src/app/_components/Modal/ModalHeader.tsx
  src/app/_components/Modal/ModalLayout.tsx
  src/app/_components/Modal/ModalMainContent.tsx
  src/app/_components/Modal/ModalOutside.tsx
  src/app/_components/Modal/ModalPortal.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_components/index.ts
  src/app/_hooks/useMediaQueries.tsx
  src/app/_styles/datePicker.css
  src/app/_utils/formatDate.ts
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: 🚀 기능 구현

#31 [#30] fix: css 수정
  src/app/_components/Hero/index.tsx
  src/app/globals.css
Labels: 🐞 버그

#34 [#29] fix: onboarding page header 깨짐문제
  src/app/(onboarding)/_components/OnboardingHeader.tsx
  src/app/(onboarding)/onboard/page.tsx
  src/app/(onboarding)/onboard/question/page.tsx
  src/app/_components/Button/CircleButton.tsx
  src/app/_components/Button/RoundButton.tsx
  src/app/_components/Footer/index.tsx
  src/app/_components/Header/index.tsx
  src/app/globals.css
Labels: 🐞 버그

#39 fix: husky.sh 파일 누락 문제 해결
  .husky/_/husky.sh
  package-lock.json
  package.json
Labels: 🐞 버그

#37 [#36] chore: 리드미 초안 작성
  README.md
Labels: 🌻 기타수정사항

#47 [#43] feat: 검색 페이지 캠핑장 목록 ui 구현
  public/data/campPlaceForMapMockData.json
  public/svgs/index.ts
  public/svgs/navigationDown.svg
  public/svgs/navigationLeft.svg
  public/svgs/navigationRight.svg
  public/svgs/navigationUp.svg
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/_components/CampSearchList.tsx
  src/app/(header&footer)/_components/SearchPagination.tsx
  src/app/(header&footer)/_components/SortDropdown.tsx
  src/app/(header&footer)/search/page.tsx
  src/app/_components/CategoryList.tsx
  src/app/_components/index.ts
  tailwind.config.ts
Labels: 🚀 기능 구현
