Repository teamCampro/campro_FE, pull requests merged in 2024-02, with the labels that each got.

#50 [#49] : 지도 검색 페이지 캠핑장목록 페이지네이션 구현 및 모달&드롭다운 css 수정
  public/data/campPlaceForMapMockData.json
  src/app/(header&footer)/_components/CampSearchList.tsx
  src/app/(header&footer)/_components/SearchPagination.tsx
  src/app/(header&footer)/search/page.tsx
  src/app/_components/Controller/DatePickerController.tsx
  src/app/_components/Dropdown/GroupDropdown.tsx
  src/app/_components/Dropdown/LocationDropdown.tsx
  src/app/_components/Hero/index.tsx
  src/app/_components/Input/DateInputView.tsx
  src/app/_components/Input/GroupCountInputView.tsx
  src/app/_components/Input/LocationInputView.tsx
  src/app/_components/Modal/ModalForMobile.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_hooks/useMediaQueries.tsx
  src/app/_styles/datePicker.css
Labels: 🌻 기타수정사항

#52 [#45] feat: 지도 검색페이지 지도 컴포넌트 구현
  package-lock.json
  package.json
  public/data/mapPositionsMockData.json
  public/svgs/index.ts
  public/svgs/leftGray.svg
  public/svgs/mapMinus.svg
  public/svgs/mapPlus.svg
  public/svgs/rightGray.svg
  src/app/(header&footer)/_components/CampSearchList.tsx
  src/app/(header&footer)/search/page.tsx
  src/app/(header)/.gitkeep
  src/app/(header)/_components/CampSearchList.tsx
  src/app/(header)/_components/KakaoMap.tsx
  src/app/(header)/_components/KakaoOverlay.tsx
  src/app/(header)/_components/SearchPagination.tsx
  src/app/(header)/_components/SortDropdown.tsx
  src/app/(header)/layout.tsx
  src/app/(header)/search/page.tsx
  src/app/_components/Button/RoundArrowButton.tsx
  src/app/_components/Button/index.tsx
  src/app/_components/Header/index.tsx
  src/app/_components/index.ts
  src/app/_utils/kakaoMarkerGenerator.css
  src/app/_utils/kakaoMarkerGenerator.ts
  src/app/layout.tsx
  tsconfig.json
Labels: 🚀 기능 구현

#53 [#44] feat: 지도 검색페이지 상세필터 컴포넌트
  public/svgs/arrowDown.svg
  public/svgs/arrowUp.svg
  public/svgs/filter.svg
  public/svgs/index.ts
  public/svgs/reset.svg
  src/app/(header&footer)/.gitkeep
  src/app/(header)/mapTest/_components/DeTailList.tsx
  src/app/(header)/mapTest/_components/DetailPanel.tsx
  src/app/(header)/mapTest/_components/ModalDetailList.tsx
  src/app/(header)/mapTest/page.tsx
  src/app/_components/Button/CircleButton.tsx
  src/app/_components/Controller/DatePickerController.tsx
  src/app/_components/Dropdown/Selectable.tsx
  src/app/_components/Dropdown/_components/PriceInput.tsx
  src/app/_components/Dropdown/_components/PriceTable.tsx
  src/app/_components/Dropdown/_components/SelectList.tsx
  src/app/_components/Modal/ModalLayout.tsx
  src/app/_components/Modal/ModalOutside.tsx
  src/app/_components/checkBox/index.tsx
  src/app/_components/index.ts
  src/app/_constants/.gitkeep
  src/app/_constants/detail.ts
  src/app/_constants/index.ts
  src/app/_hooks/.gitkeep
  src/app/_store/store.ts
  src/app/_styles/datePicker.css
  src/app/_utils/detailState.ts
  src/app/_utils/modalState.ts
  src/app/_utils/styleSetting.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#57 [#54] chore: 지도페이지 layout (검색 쪽 수정 필요)
  src/app/(header)/_components/DeTailList.tsx
  src/app/(header)/_components/DetailButtons.tsx
  src/app/(header)/_components/DetailPanel.tsx
  src/app/(header)/_components/ModalDetailList.tsx
  src/app/(header)/_components/SearchFilter.tsx
  src/app/(header)/mapTest/_components/DetailPanel.tsx
  src/app/(header)/search/page.tsx
  src/app/_components/Dropdown/Selectable.tsx
Labels: 🌻 기타수정사항

#58 [#44] fix: 지도 검색페이지 상세필터
  public/svgs/checkboxOff.svg
  public/svgs/checkboxOn.svg
  public/svgs/index.ts
  src/app/(header)/_components/DetailPanel.tsx
  src/app/(header)/_components/SearchFilter.tsx
  src/app/(header)/search/page.tsx
  src/app/_components/Dropdown/Selectable.tsx
  src/app/_components/Dropdown/_components/SelectList.tsx
  src/app/_utils/styleSetting.ts
  src/app/globals.css
Labels: 🐞 버그, 🌻 기타수정사항

#60 [#51] feat : 공통 폼 및 인풋 컴포넌트 기능 추가 및 로그인/회원가입 폼 구현 + 검색바 라우팅
  src/app/(header)/search/page.tsx
  src/app/(sign)/signin/page.tsx
  src/app/(sign)/signup/page.tsx
  src/app/_components/Controller/DatePickerController.tsx
  src/app/_components/Controller/LocationController.tsx
  src/app/_components/Dropdown/GroupDropdown.tsx
  src/app/_components/Form/CommonForm.tsx
  src/app/_components/Hero/index.tsx
  src/app/_components/Input/AboutInput/ErrorMessage.tsx
  src/app/_components/Input/AboutInput/InputContainer.tsx
  src/app/_components/Input/AboutInput/Label.tsx
  src/app/_components/Input/CommonInput.tsx
  src/app/_components/SearchBar/SearchBarForMap.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_components/index.ts
  src/app/_constants/inputValidate.ts
  src/app/_styles/datePicker.css
Labels: 🚀 기능 구현

#59 [#56] refactor: 지도 마커 이미지, 버튼, 오버레이 디자인 수정
  public/svgs/index.ts
  public/svgs/list.svg
  public/svgs/listAndMap.svg
  public/svgs/map.svg
  public/svgs/markerGray.svg
  public/svgs/markerGreen.svg
  public/svgs/score.svg
  src/app/(header)/_components/KakaoMap.tsx
  src/app/(header)/_components/KakaoOverlay.tsx
  src/app/(header)/search/page.tsx
  src/app/_components/Button/MapFloatingButton.tsx
  src/app/_components/Button/index.tsx
  src/app/_utils/createCustomOverlay.ts
  src/app/_utils/createMapPosition.ts
  src/app/_utils/createMarkerImage.ts
  src/app/_utils/createOverlayElement.ts
  src/app/_utils/kakaoMarkerGenerator.css
  src/app/_utils/kakaoMarkerGenerator.ts
Labels: 🚀 기능 구현, 🔨 리팩토링

#64 [#61] fix: 검색바 배치 변경 및 css 수정
  package-lock.json
  public/avifs/sign.avif
  src/app/(header)/_components/CampSearchList.tsx
  src/app/(header)/layout.tsx
  src/app/(header)/search/page.tsx
  src/app/(sign)/signin/page.tsx
  src/app/(sign)/signup/page.tsx
  src/app/_components/Controller/DatePickerController.tsx
  src/app/_components/DatePicker/ButtonSetForDatePicker.tsx
  src/app/_components/DatePicker/CustomHeaderForDatePicker.tsx
  src/app/_components/DatePicker/DateInputView.tsx
  src/app/_components/Form/CommonForm.tsx
  src/app/_components/Form/LoginForm.tsx
  src/app/_components/Form/SignUpForm.tsx
  src/app/_components/Header/index.tsx
  src/app/_components/Hero/HeroForSign.tsx
  src/app/_components/Input/AboutInput/Label.tsx
  src/app/_components/Input/CommonInput.tsx
  src/app/_components/Input/LocationInputView.tsx
  src/app/_components/Modal/ModalOutside.tsx
  src/app/_components/SearchBar/SearchBarForMap.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_components/index.ts
  src/app/_constants/inputStyle.tsx
  src/app/_styles/datePicker.css
  src/app/_utils/getFormattedDate.ts
  tailwind.config.ts
Labels: 🌻 기타수정사항

#67 [#55] feat: 검색페이지 상세 필터 기능
  public/svgs/arrowRight-non.svg
  src/app/(header&footer)/page.tsx
  src/app/(header)/_components/DeTailList.tsx
  src/app/(header)/_components/DetailButtons.tsx
  src/app/(header)/search/_components/CampSearchList.tsx
  src/app/(header)/search/_components/DetailPanel.tsx
  src/app/(header)/search/_components/KakaoMap.tsx
  src/app/(header)/search/_components/KakaoOverlay.tsx
  src/app/(header)/search/_components/ModalDetailList.tsx
  src/app/(header)/search/_components/SearchFilter.tsx
  src/app/(header)/search/_components/SearchPagination.tsx
  src/app/(header)/search/page.tsx
  src/app/_components/Button/CircleButton.tsx
  src/app/_components/Button/RoundButton.tsx
  src/app/_components/Controller/DatePickerController.tsx
  src/app/_components/DatePicker/DateInputView.tsx
  src/app/_components/Dropdown/Selectable.tsx
  src/app/_components/Dropdown/_components/PriceInput.tsx
  src/app/_components/Dropdown/_components/PriceTable.tsx
  src/app/_components/Dropdown/_components/SelectList.tsx
  src/app/_components/Footer/index.tsx
  src/app/_components/Form/CommonForm.tsx
  src/app/_components/Hero/index.tsx
  src/app/_components/Input/GroupCountInputView.tsx
  src/app/_components/Input/LocationInputView.tsx
  src/app/_components/Modal/ModalFooter.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_components/checkBox/index.tsx
  src/app/_components/index.ts
  src/app/_constants/detail.ts
  src/app/_constants/inputStyle.tsx
  src/app/_store/store.ts
  src/app/_utils/checkStandByState.ts
  src/app/_utils/detailState.ts
  src/app/_utils/numberFormatter.ts
  src/app/_utils/styleSetting.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#68 [#65] : feat: 로그인/회원가입 스타일 추가 및 체크박스 컴포넌트 구현
  public/avifs/sign.avif
  public/fonts/Preahvihear-Regular.ttf
  public/svgs/Google.svg
  public/svgs/Kakao.svg
  public/svgs/checkbox.svg
  public/svgs/checkboxEmpty.svg
  public/svgs/naver.svg
  src/app/(sign)/signin/page.tsx
  src/app/(sign)/signup/page.tsx
  src/app/_components/Button/SocialLoginButtonSet.tsx
  src/app/_components/Form/LoginForm.tsx
  src/app/_components/Form/SignUpForm.tsx
  src/app/_components/Input/AboutInput/ErrorMessage.tsx
  src/app/_components/Input/CommonInput.tsx
  src/app/_components/checkBox/SignUpCheckBox.tsx
  src/app/_constants/inputValidate.ts
  src/app/_styles/datePicker.css
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#70 [#69] chore: 상세페이지 폴더 추가
  src/app/(header&footer)/overview/page.tsx
  src/app/globals.css
Labels: 🌻 기타수정사항

#77 [#72] fix: 지도 페이지 수정(스타일)
  src/app/(header)/search/_components/DetailPanel.tsx
  src/app/(header)/search/_components/ModalDetailList.tsx
  src/app/(header)/search/_components/SearchFilter.tsx
  src/app/_components/Dropdown/Selectable.tsx
  src/app/_components/Dropdown/_components/PriceInput.tsx
  src/app/_components/Dropdown/_components/PriceTable.tsx
  src/app/_components/Hero/index.tsx
  src/app/_components/Modal/ModalFooter.tsx
  src/app/_components/Modal/ModalHeader.tsx
  src/app/_components/Modal/ModalLayout.tsx
  src/app/_components/Modal/ModalMainContent.tsx
  src/app/_components/Modal/ModalOutside.tsx
  src/app/_components/SearchBar/index.tsx
  tailwind.config.ts
Labels: 🌻 기타수정사항

#80 [#71] feat : 캠핑장 상세 페이지 이미지캐러셀 컴포넌트 구현
  public/data/campImageMockData.json
  public/svgs/exit.svg
  public/svgs/pic.svg
  src/app/(header&footer)/_components/CampImage/CampImageCarousel.tsx
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/_components/CampImage/Modal/CampImageForModal.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalAboutCampImage.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalAboutHeader.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalForMobileCampImg.tsx
  src/app/(header&footer)/_components/CampImage/index.tsx
  src/app/(header&footer)/overview/page.tsx
  src/app/_components/Modal/ModalOutside.tsx
  src/app/_styles/carousel.css
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: 🚀 기능 구현

#82 [#81] fix: 로그인/회원가입 변경된 디자인으로 수정
  src/app/(sign)/signin/page.tsx
  src/app/(sign)/signup/page.tsx
  tailwind.config.ts
Labels: 🌻 기타수정사항

#84 [#78] feat: 캠핑장 상세페이지 미니 지도
  public/svgs/copy.svg
  public/svgs/exit.svg
  public/svgs/fullPage.svg
  public/svgs/index.ts
  src/app/(header&footer)/_components/MiniMapContainer.tsx
  src/app/(header&footer)/_components/MinikakaoMap.tsx
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/page.tsx
  src/app/_components/Modal/ModalFooter.tsx
  src/app/_components/Modal/ModalHeader.tsx
  src/app/_components/Modal/ModalLayout.tsx
  src/app/_components/Modal/ModalMainContent.tsx
  src/app/_types/.gitkeep
  src/app/layout.tsx
  tailwind.config.ts
Labels: 🚀 기능 구현

#87 [#83] feat: 검색바 필터 기능 추가
  package-lock.json
  package.json
  src/app/_components/Controller/DatePickerController.tsx
  src/app/_components/Dropdown/LocationDropdown.tsx
  src/app/_components/Input/GroupCountInputView.tsx
  src/app/_components/Input/LocationInputView.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
  src/app/_styles/datePicker.css
Labels: 🚀 기능 구현

#90 [#86] feat: 상세페이지 Layout [미완성]
  public/avifs/map.avif
  public/data/bossText.json
  public/data/keywordMockData.json
  public/svgs/call.svg
  public/svgs/index.ts
  public/svgs/location.svg
  public/svgs/star.svg
  src/app/(header&footer)/_components/MiniMapContainer.tsx
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/Progress.tsx
  src/app/(header&footer)/overview/_components/TextInfo.tsx
  src/app/_components/Category/index.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#95 [#94]: 폰트 디자인 시스템
  tailwind.config.ts
Labels: 🌻 기타수정사항

#99 [#97] feat: 캠핑장 상세 페이지 검색바 내 인풋 변경
  public/svgs/location.svg
  src/app/_components/Controller/PlaceController.tsx
  src/app/_components/Input/PlaceInputView.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/index.tsx
Labels: 🚀 기능 구현

#100 [#92] feat: 예약&결제 페이지 layout
  public/svgs/arrowLeft-non.svg
  public/svgs/index.ts
  public/svgs/plus-non.svg
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(header&footer)/reserve/page.tsx
  src/app/_components/Footer/index.tsx
  src/app/_components/Header/index.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#101 [#86] feat: 상세 페이지 레이아웃 [미완성]
  public/svgs/arrowDown.svg
  public/svgs/index.ts
  src/app/(header&footer)/_components/CampImage/CampImageCarousel.tsx
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/_components/MiniMapContainer.tsx
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/CampSiteBasicInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteBookingInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteBossInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteDetail.tsx
  src/app/(header&footer)/overview/_components/CampSiteItem.tsx
  src/app/(header&footer)/overview/_components/CampSiteList.tsx
  src/app/(header&footer)/overview/_components/CampSiteProfile.tsx
  src/app/(header&footer)/overview/_components/Review.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(header&footer)/reserve/page.tsx
  src/app/_components/Category/index.tsx
  src/app/_components/CategoryItem.tsx
  src/app/_components/Copy/index.tsx
  src/app/_components/Footer/index.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#103 [#102] fix: 변경된 디자인시스템에 맞게 폰트 수정
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/_components/CampPlaceList.tsx
  src/app/(header&footer)/_components/MiniMapContainer.tsx
  src/app/(header&footer)/overview/_components/CampSiteBasicInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteBookingInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteBossInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteDetail.tsx
  src/app/(header&footer)/overview/_components/SiteInfoList.tsx
  src/app/(header&footer)/overview/_components/TextInfo.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(header&footer)/reserve/page.tsx
  src/app/(header)/search/_components/MapSizeButtons.tsx
  src/app/(header)/search/_components/SearchPagination.tsx
  src/app/(header)/search/_components/SortDropdown.tsx
  src/app/(header)/search/page.tsx
  src/app/(onboarding)/_components/OnboardingHeader.tsx
  src/app/(onboarding)/_components/OnboardingItem.tsx
  src/app/(onboarding)/_components/OnboardingList.tsx
  src/app/(onboarding)/onboard/page.tsx
  src/app/(onboarding)/onboard/question/page.tsx
  src/app/(sign)/signin/page.tsx
  src/app/(sign)/signup/page.tsx
  src/app/_components/Button/MapFloatingButton.tsx
  src/app/_components/Button/RoundButton.tsx
  src/app/_components/Button/SocialLoginButtonSet.tsx
  src/app/_components/CategoryList.tsx
  src/app/_components/DatePicker/DateInputView.tsx
  src/app/_components/Dropdown/GroupDropdown.tsx
  src/app/_components/Dropdown/Selectable.tsx
  src/app/_components/Dropdown/_components/PriceInput.tsx
  src/app/_components/Dropdown/_components/SelectList.tsx
  src/app/_components/Footer/index.tsx
  src/app/_components/Form/LoginForm.tsx
  src/app/_components/Form/SignUpForm.tsx
  src/app/_components/Hero/index.tsx
  src/app/_components/Input/GroupCountInputView.tsx
  src/app/_components/Input/LocationInputView.tsx
  src/app/_components/Input/PlaceInputView.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
  tailwind.config.ts
Labels: 🌻 기타수정사항

#93 fix: 검색페이지 지도 두번 렌더링 되는 문제
  src/app/(header)/search/_components/KakaoMap.tsx
Labels: 🐞 버그

#106 [#105] 검색페이지 목록 잘리는 현상 수정
  src/app/(header)/search/page.tsx
Labels: 🐞 버그

#108 [#104] feat: 각 페이지 기능 연결(미완)
  src/app/(header&footer)/_components/MinikakaoMap.tsx
  src/app/(header)/search/_components/KakaoMap.tsx
  src/app/(header)/search/page.tsx
  src/app/(sign)/signin/page.tsx
  src/app/_components/Dropdown/Selectable.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
Labels: 🚀 기능 구현

#111 [#109] feat: 마이페이지 Layout
  public/svgs/people.svg
  src/app/(mypage)/profile/_components/ProfileHeader.tsx
  src/app/(mypage)/profile/_components/ProfileInfo.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/(mypage)/profile/_components/ReserveItem.tsx
  src/app/(mypage)/profile/_components/ReserveList.tsx
  src/app/(mypage)/profile/_components/ReserveStateLists.tsx
  src/app/(mypage)/profile/_components/SideLists.tsx
  src/app/(mypage)/profile/layout.tsx
  src/app/(mypage)/profile/page.tsx
  src/app/(mypage)/profile/reserveList/[id]/page.tsx
  src/app/(mypage)/profile/reserveList/page.tsx
  src/app/(mypage)/profile/setting/page.tsx
  src/app/(onboarding)/_components/OnboardingHeader.tsx
  src/app/(sign)/signup/page.tsx
  src/app/_components/Footer/index.tsx
  src/app/_components/Header/_components/HeaderDropdown.tsx
  src/app/_components/Header/_components/HeaderModal.tsx
  src/app/_components/Header/index.tsx
  src/app/_store/store.ts
  src/app/_utils/profileState.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#112 [#107] : 예약페이지 기능 구현
  public/svgs/deleteVehicle.svg
  public/svgs/left.svg
  src/app/(header&footer)/reserve/_components/AddOption.tsx
  src/app/(header&footer)/reserve/_components/AddVehicle.tsx
  src/app/(header&footer)/reserve/_components/HeaderAboutReserve.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutBookingPerson.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutReserve.tsx
  src/app/(header&footer)/reserve/_components/PaymentAmount.tsx
  src/app/(header&footer)/reserve/_components/PaymentMethod.tsx
  src/app/(header&footer)/reserve/_components/PaymentSubmit.tsx
  src/app/(header&footer)/reserve/_components/TermsAgreement.tsx
  src/app/(header&footer)/reserve/_components/TotalPayment.tsx
  src/app/(header&footer)/reserve/page.tsx
  src/app/(header)/search/page.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_slices/paymentMethod.ts
  src/app/_slices/plusOptions.ts
  src/app/_slices/reserveInfo.ts
  src/app/_slices/totalPayment.ts
  src/app/_slices/vehicleNumber.ts
  src/app/_store/store.ts
Labels: 🚀 기능 구현

#117 [#116] : url파라미터 수정
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/page.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutBookingPerson.tsx
  src/app/_components/Hero/index.tsx
  src/app/_components/Input/GroupCountInputView.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_utils/getSearchBarValue.ts
  src/app/_utils/submitForSearchBar.ts
Labels: 🌻 기타수정사항

#119 [#115] mock 데이터 생성 [미완성]
  makeMock.js
  public/data/overviewMockData.json
  public/data/overviewMockDataback.json
  public/data/searchPageMockData.json
  public/svgs/people.svg
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/_components/CampPlaceList.tsx
  src/app/(header&footer)/_components/MiniMapContainer.tsx
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/AnchorMenu.tsx
  src/app/(header&footer)/overview/_components/CampSiteBasicInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteBookingInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteDetail.tsx
  src/app/(header&footer)/overview/_components/CampSiteFacilities.tsx
  src/app/(header&footer)/overview/_components/CampSiteItem.tsx
  src/app/(header&footer)/overview/_components/CampSiteList.tsx
  src/app/(header&footer)/overview/_components/CampSiteMap.tsx
  src/app/(header&footer)/overview/_components/CustomerReviews.tsx
  src/app/(header&footer)/overview/_components/ReservationInfo.tsx
  src/app/(header&footer)/overview/_components/ReviewItem.tsx
  src/app/(header&footer)/overview/_components/SectionRef.tsx
  src/app/(header&footer)/overview/_components/UsageGuidelines.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
Labels: 🌻 기타수정사항

#120 [#118] : 예약 페이지 내 결제하기 모달 및 약관동의 드롭다운 구현
  src/app/(header&footer)/overview/_components/CampSiteItem.tsx
  src/app/(header&footer)/reserve/_components/ModalForPaymentSubmit.tsx
  src/app/(header&footer)/reserve/_components/PaymentSubmit.tsx
  src/app/(header&footer)/reserve/_components/TermsAgreement.tsx
  src/app/_slices/isAllChecked.ts
  src/app/_store/store.ts
Labels: 🚀 기능 구현

#123 [#109] feat: 마이페이지 Layout
  public/svgs/close.svg
  public/svgs/index.ts
  public/svgs/plus-non.svg
  public/svgs/star-gray.svg
  public/svgs/star-half.svg
  src/app/(header&footer)/reserve/_components/PaymentAmount.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(header&footer)/reserve/page.tsx
  src/app/(mypage)/profile/_components/CancleReserverModal.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/(mypage)/profile/_components/ReserveItem.tsx
  src/app/(mypage)/profile/_components/Score.tsx
  src/app/(mypage)/profile/_components/SideLists.tsx
  src/app/(mypage)/profile/_components/Survey.tsx
  src/app/(mypage)/profile/_components/WriteReview.tsx
  src/app/(mypage)/profile/_components/WriteReviewModal.tsx
  src/app/globals.css
Labels: 🚀 기능 구현

#124 [#121] : 메인, 지도, 캠핑장 상세, 예약하기 페이지 연결
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/AnchorMenu.tsx
  src/app/(header&footer)/overview/_components/CampSiteItem.tsx
  src/app/(header&footer)/reserve/[campId]/[siteId]/page.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutReserve.tsx
  src/app/(header&footer)/reserve/_components/TermsAgreement.tsx
  src/app/_components/CategoryItem.tsx
  src/app/_components/CategoryList.tsx
  src/app/_components/Controller/LocationController.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_constants/links.tsx
  src/app/_utils/formatDate.ts
  src/app/_utils/getSearchBarValue.ts
  src/app/_utils/submitForSearchBar.ts
Labels: 🚀 기능 구현

#134 [#72] fix: 지도페이지 수정
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header)/search/_components/KakaoMap.tsx
  src/app/(header)/search/page.tsx
Labels: 🚀 기능 구현, 🌻 기타수정사항

#135 [#72] fix: 지도페이지 수정(style)
  public/data/mapPositionsMockData.json
  src/app/(header)/search/_components/SearchPagination.tsx
  src/app/(header)/search/page.tsx
Labels: 🌻 기타수정사항

#130 [#74] fix: 온보딩 페이지
  public/gifs/campro_loading.gif
  public/svgs/ArrowLeftGray.svg
  src/app/(onboarding)/onboard/question/page.tsx
  src/app/_components/Pagination.tsx
Labels: 🔨 리팩토링

#132 [#73] fix: 메인 페이지
  public/svgs/arrowLeft-non.svg
  public/svgs/coloredHeart.svg
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/_components/CampPlaceList.tsx
  src/app/_components/CategoryItem.tsx
  src/app/_components/DatePicker/CustomHeaderForDatePicker.tsx
  src/app/_styles/datePicker.css
Labels: 🔨 리팩토링

#138 [#127] 예약하기 페이지
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/reserve/[campId]/[siteId]/page.tsx
  src/app/(header&footer)/reserve/_components/AddOption.tsx
  src/app/(header&footer)/reserve/_components/AddVehicle.tsx
  src/app/(header&footer)/reserve/_components/HeaderAboutReserve.tsx
  src/app/(header&footer)/reserve/_components/HeaderContent.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/(header&footer)/reserve/_components/PaymentAmount.tsx
  src/app/(header&footer)/reserve/_components/PaymentMethod.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/_components/Controller/GroupCountController.tsx
  src/app/_components/Form/CommonForm.tsx
  src/app/_components/Input/GroupCountInputView.tsx
  src/app/_components/Modal/ModalForMobile.tsx
  src/app/_components/Modal/ModalForSearchBar.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
  src/app/_components/SearchBar/index.tsx
  src/app/_utils/submitForSearchBar.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현

#143 [#127] : 예약하기 페이지 및 각 종 체크 해결
  src/app/(header&footer)/_components/CampImage/CampImageCarousel.tsx
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/_components/CampImage/Modal/CampImageForModal.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalAboutCampImage.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalForMobileCampImg.tsx
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/reserve/_components/AddOption.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(header)/search/_components/KakaoMap.tsx
  src/app/_components/Copy/index.tsx
  src/app/_components/Hero/index.tsx
  src/app/_components/Modal/ModalForSearchBar.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
  src/app/_components/Toast/ClipboardToast.tsx
  src/app/_styles/toast.css
  src/app/_utils/submitForSearchBar.ts
  tailwind.config.ts
Labels: 🚀 기능 구현

#153 [#152] fix: commonInput validate 안되는 문제
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/_components/Input/CommonInput.tsx
Labels: 🐞 버그

#145 [#129] fix: 마이 페이지(완료)
  public/data/reserveListMockData.json
  src/app/(header&footer)/_components/CampImage/index.tsx
  src/app/(header&footer)/overview/_components/CampSiteItem.tsx
  src/app/(header&footer)/overview/_components/TextInfo.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutReserve.tsx
  src/app/(header&footer)/reserve/_components/PaymentSubmit.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(header)/search/_components/SearchPagination.tsx
  src/app/(header)/search/page.tsx
  src/app/(mypage)/profile/_components/ImageUpload.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/(mypage)/profile/_components/ReserveItem.tsx
  src/app/(mypage)/profile/_components/ReserveList.tsx
  src/app/(mypage)/profile/_components/ReserveStateLists.tsx
  src/app/(mypage)/profile/_components/Score.tsx
  src/app/(mypage)/profile/_components/SideLists.tsx
  src/app/(mypage)/profile/_components/Survey.tsx
  src/app/(mypage)/profile/_components/WriteReview.tsx
  src/app/(mypage)/profile/_components/WriteReviewModal.tsx
  src/app/(mypage)/profile/reserveList/[id]/page.tsx
  src/app/(mypage)/profile/reserveList/page.tsx
  src/app/(owner)/_constants/common.ts
  src/app/_constants/reserveList.ts
  src/app/_utils/getOneFormatDate.ts
  src/app/_utils/profileState.ts
Labels: 🚀 기능 구현, 🌻 기타수정사항

#156 [#144] : 메인 및 지도검색 페이지 api 연결
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/_components/CampPlaceList.tsx
  src/app/(header&footer)/_components/CampPlaceSection.tsx
  src/app/(header&footer)/page.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/(header)/search/_components/CampSearchList.tsx
  src/app/(header)/search/_components/KakaoMap.tsx
  src/app/(header)/search/page.tsx
  src/app/_components/Chip.tsx
  src/app/_components/Form/CommonForm.tsx
  src/app/_utils/createMapPosition.ts
  src/app/_utils/kakaoMarkerGenerator.ts
  src/app/api/camping-zone/list/route.ts
Labels: 🚀 기능 구현

#158 [#148] feat: 회원가입 API 연결
  src/app/(sign)/signup/page.tsx
  src/app/_components/Form/SignUpForm.tsx
  src/app/_components/checkBox/SignUpCheckBox.tsx
  src/app/_constants/inputValidate.ts
  src/app/_data/sign/signup.ts
  src/app/_utils/axiosInstance.ts
Labels: 🚀 기능 구현

#159 [#144] feat: baseURL 동적으로 변하게 수정
  .gitignore
  src/app/(header&footer)/_components/CampPlaceSection.tsx
  src/app/(header&footer)/page.tsx
  src/app/(mypage)/profile/_components/ReserveItem.tsx
  src/app/(mypage)/profile/_components/ReserveList.tsx
  src/app/(mypage)/profile/layout.tsx
  src/app/(mypage)/profile/reserveList/page.tsx
  src/app/_data/main/campList.ts
  src/app/_utils/axiosInstance.ts
Labels: 🚀 기능 구현, 🌻 기타수정사항

#163 [#162] feat: 로그인 API 연동
  .gitignore
  src/app/_components/Form/LoginForm.tsx
  src/app/_data/sign/signin.ts
  src/app/_utils/axiosInstance.ts
Labels: 🚀 기능 구현

#164 [#157]: 예약하기 페이지
  .gitignore
  src/app/(header&footer)/_components/CampImage/Modal/CampImageForModal.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalAboutCampImage.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalAboutHeader.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalForMobileCampImg.tsx
  src/app/(header&footer)/reserve/_components/AddVehicle.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/(header&footer)/reserve/_components/PaymentSubmit.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/_components/Input/CommonInput.tsx
  src/app/_constants/inputValidate.ts
Labels: 🚀 기능 구현

#166 [#157- 2] : search페이지 url 수정
  src/app/(header)/search/page.tsx
Labels: 🐞 버그

#167 [#157- 3]: axiosInstance 수정
  src/app/(header)/search/page.tsx
Labels: 🐞 버그

#175 [#171] fix: 모든 버튼 수정
  public/svgs/campro_simbol.svg
  src/app/(header&footer)/_components/CampImage/CampImageCarousel.tsx
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/_components/CampImage/Modal/CampImageForModal.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalForMobileCampImg.tsx
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/reserve/_components/PaymentSubmit.tsx
  src/app/(header)/search/_components/SearchFilter.tsx
  src/app/(mypage)/profile/_components/ReserveItem.tsx
  src/app/(mypage)/profile/_components/WriteReviewModal.tsx
  src/app/(sign)/signin/page.tsx
  src/app/_components/Button/HookFormButton.tsx
  src/app/_components/Controller/LocationController.tsx
  src/app/_components/Copy/index.tsx
  src/app/_components/Dropdown/Selectable.tsx
  src/app/_components/Form/CommonForm.tsx
  src/app/_components/Form/LoginForm.tsx
  src/app/_components/Header/_components/HeaderDropdown.tsx
  src/app/_components/Header/_components/HeaderModal.tsx
  src/app/_components/Input/LocationInputView.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
  src/app/_components/SearchBar/index.tsx
Labels: 🌻 기타수정사항

#177 [#161] 상세 페이지 API 연동
  public/svgs/airConditional.svg
  public/svgs/autoCamping.svg
  public/svgs/bbq.svg
  public/svgs/bed.svg
  public/svgs/campingCar.svg
  public/svgs/campnic.svg
  public/svgs/chabak.svg
  public/svgs/cooking.svg
  public/svgs/electricity.svg
  public/svgs/exercise.svg
  public/svgs/heating.svg
  public/svgs/index.ts
  public/svgs/kidsCamping.svg
  public/svgs/personalShower.svg
  public/svgs/personalToilet.svg
  public/svgs/pet.svg
  public/svgs/play.svg
  public/svgs/publicToilet.svg
  public/svgs/rental.svg
  public/svgs/shower.svg
  public/svgs/sink.svg
  public/svgs/store.svg
  public/svgs/trampoline.svg
  public/svgs/tv.svg
  public/svgs/walkingPath.svg
  public/svgs/waterPlay.svg
  public/svgs/wifi.svg
  src/app/(header&footer)/_components/CampImage/CampImageCarousel.tsx
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/_components/CampImage/Modal/CampImageForModal.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalAboutCampImage.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalAboutHeader.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalForMobileCampImg.tsx
  src/app/(header&footer)/_components/CampImage/index.tsx
  src/app/(header&footer)/_components/MiniMapContainer.tsx
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/AnchorMenu.tsx
  src/app/(header&footer)/overview/_components/CampSiteBasicInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteBookingInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteDetail.tsx
  src/app/(header&footer)/overview/_components/CampSiteFacilities.tsx
  src/app/(header&footer)/overview/_components/CampSiteItem.tsx
  src/app/(header&footer)/overview/_components/CampSiteMap.tsx
  src/app/(header&footer)/overview/_components/CustomerReviews.tsx
  src/app/(header&footer)/overview/_components/ReservationInfo.tsx
  src/app/(header&footer)/overview/_components/ReviewItem.tsx
  src/app/(header&footer)/overview/_components/UsageGuidelines.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/_components/Button/HookFormButton.tsx
  src/app/_components/CategoryItem.tsx
  src/app/_components/CategoryList.tsx
  src/app/_components/Copy/index.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_constants/facilities.tsx
  src/app/_constants/links.tsx
  src/app/_data/overview/overview.ts
  src/app/_hooks/useDebounce.ts
  src/app/api/camping-zone/[campingZoneId]/route.ts
  src/app/globals.css
Labels: 🚀 기능 구현

#178 [#171] fix: 모든 버튼 수정
  src/app/_components/Button/HookFormButton.tsx
  src/app/_components/Form/SignUpForm.tsx
Labels: 🌻 기타수정사항

#181 [#72] 지도 검색 페이지 클러스터 적용
  src/app/(header)/search/_components/KakaoMap.tsx
  src/app/(header)/search/page.tsx
  src/app/_utils/createMapPosition.ts
  src/app/_utils/createOverlayElement.ts
  src/app/_utils/kakaoMarkerGenerator.ts
  src/app/layout.tsx
Labels: 🚀 기능 구현, 🔨 리팩토링, 🐞 버그

#183 [#171] fix: 모든 버튼 수정
  src/app/(header&footer)/overview/[id]/layout.tsx
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/AnchorMenu.tsx
  src/app/(header&footer)/overview/_components/CampSiteFacilities.tsx
  src/app/(header&footer)/reserve/[campId]/[siteId]/page.tsx
  src/app/(header&footer)/reserve/_components/AddVehicle.tsx
  src/app/(header&footer)/reserve/_components/HeaderAboutReserve.tsx
  src/app/(header&footer)/reserve/_components/PaymentSubmit.tsx
  src/app/(header&footer)/reserve/_components/TermsAgreement.tsx
  src/app/(header)/search/_components/SearchPagination.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/(mypage)/profile/_components/Survey.tsx
  src/app/(mypage)/profile/_components/WriteReviewModal.tsx
  src/app/_components/Header/_components/HeaderDropdown.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
  src/app/_components/SearchBar/index.tsx
Labels: 🌻 기타수정사항

#185 [#184] 상세페이지 옵저버 수정
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/AnchorMenu.tsx
  src/app/(header&footer)/overview/_components/ReviewItem.tsx
  src/app/_utils/getTimeDiff.ts
Labels: 🐞 버그

#187 [#180] : 캐러셀 라이트박스 추가
  src/app/(header&footer)/_components/CampImage/CampImageCarousel.tsx
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/_components/CampImage/Modal/CampImageForModal.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalAboutHeader.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalForMobileCampImg.tsx
  src/app/(header&footer)/_components/CampImage/index.tsx
  src/app/(header&footer)/reserve/_components/AddOption.tsx
  src/app/(header&footer)/reserve/_components/AddVehicle.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(header)/search/_components/KakaoMap.tsx
  src/app/_components/Dropdown/Selectable.tsx
  src/app/_components/Input/AboutInput/ErrorMessage.tsx
  src/app/_constants/inputValidate.ts
  src/app/_data/overview/overview.ts
  src/app/_slices/plusOptions.ts
  src/app/_styles/carousel.css
Labels: 🚀 기능 구현

#189 [#188] 검색 페이지 로딩 이미지
  src/app/(header)/layout.tsx
  src/app/(header)/search/loading.tsx
  src/app/(header)/search/page.tsx
Labels: 🐞 버그

#196 [#179] 유저 정보 API 연동
  package-lock.json
  src/app/(header&footer)/reserve/_components/InfoAboutBookingPerson.tsx
  src/app/_components/Form/LoginForm.tsx
  src/app/_components/Form/SignUpForm.tsx
  src/app/_components/Header/_components/HeaderDropdown.tsx
  src/app/_components/Header/_components/HeaderModal.tsx
  src/app/_components/checkBox/SignUpCheckBox.tsx
  src/app/_components/radio/SignUpRadio.tsx
  src/app/_data/sign/getUserInfo.ts
  src/app/_data/sign/signin.ts
  src/app/_data/sign/signup.ts
Labels: 🚀 기능 구현

#198 [#194]: 예약하기 페이지 post 요청 구현
  package-lock.json
  src/app/(header&footer)/_components/CampImage/Modal/CampImageForModal.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalForMobileCampImg.tsx
  src/app/(header&footer)/reserve/[campId]/[siteId]/page.tsx
  src/app/(header&footer)/reserve/_components/ModalForPaymentSubmit.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/(header&footer)/reserve/_components/PaymentMethod.tsx
  src/app/(header&footer)/reserve/_components/PaymentSubmit.tsx
  src/app/(header)/search/page.tsx
  src/app/_data/reserve/postReservationDetail.tsx
  src/app/_slices/paymentMethod.ts
Labels: 🚀 기능 구현

#197 [#188] 검색 페이지 로딩이미지
  package-lock.json
  src/app/(header)/search/page.tsx
  src/app/api/owner/[ownerId]/reservation/list/route.ts
  src/app/api/owner/camping-zone/register/route.ts
Labels: 🐞 버그

#200 [#199] export 위치 수정, 예약하기 페이지 로그아웃
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/CampSiteFacilities.tsx
  src/app/(header&footer)/overview/_components/ReviewItem.tsx
  src/app/(header&footer)/page.tsx
  src/app/(header&footer)/reserve/[campId]/[siteId]/page.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutBookingPerson.tsx
  src/app/_components/Header/_components/HeaderDropdown.tsx
  src/app/_components/index.ts
Labels: 🔨 리팩토링

#202 [#201] export 에러 수정
  src/app/_components/index.ts
Labels: 🐞 버그

#204 [#195] feat: 마이페이지 api 연결
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/reserve/[campId]/[siteId]/page.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutBookingPerson.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutReserve.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/(mypage)/profile/_components/ReserveItem.tsx
  src/app/(mypage)/profile/_components/ReserveList.tsx
  src/app/(mypage)/profile/_components/ReserveStateLists.tsx
  src/app/(mypage)/profile/reserveList/[id]/page.tsx
  src/app/(mypage)/profile/reserveList/page.tsx
  src/app/Loading.tsx
  src/app/_components/index.ts
  src/app/_constants/reserveList.ts
  src/app/_data/profile/getOneReserve.ts
  src/app/_data/profile/getReserveList.ts
  src/app/_utils/getOneFormatDate.ts
Labels: 🚀 기능 구현, 🌻 기타수정사항

#206 [#203] : 검색바, 사진캐러셀 컴포넌트 css 수정
  src/app/(header&footer)/_components/CampImage/Modal/CampImageForModal.tsx
  src/app/_components/CategoryList.tsx
  src/app/_utils/submitForSearchBar.ts
Labels: 🐞 버그

#212 [#221] 클러스터 커스텀 스타일 적용
  public/svgs/markerClustererLarge.svg
  public/svgs/markerClustererSmall.svg
  src/app/_utils/kakaoMarkerGenerator.ts
Labels: 🔨 리팩토링

#223 [#209] : 메인 페이지 QA 수정
  public/svgs/campingCar.svg
  public/svgs/campnic.svg
  public/svgs/chabak.svg
  public/svgs/glamping.svg
  public/svgs/kidsCamping.svg
  public/svgs/pet.svg
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/_components/CampPlaceList.tsx
  src/app/(header&footer)/_components/CampPlaceSection.tsx
  src/app/(header&footer)/page.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/_components/CategoryItem.tsx
  src/app/_components/DatePicker/DateInputView.tsx
  src/app/_components/Dropdown/GroupDropdown.tsx
  src/app/_components/Dropdown/LocationDropdown.tsx
  src/app/_components/Footer/index.tsx
  src/app/_components/Input/CommonInput.tsx
  src/app/_components/Input/GroupCountInputView.tsx
  src/app/_components/Input/LocationInputView.tsx
  src/app/_components/Modal/ModalHeader.tsx
  src/app/_constants/links.tsx
  src/app/_styles/datePicker.css
  src/app/_utils/getSearchBarValue.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 🔨 리팩토링

#231 [#225]: 예약요청 페이지 QA 수정
  public/svgs/index.ts
  src/app/(header&footer)/reserve/[campId]/[siteId]/page.tsx
  src/app/(header&footer)/reserve/_components/AddOption.tsx
  src/app/(header&footer)/reserve/_components/AddVehicle.tsx
  src/app/(header&footer)/reserve/_components/HeaderAboutReserve.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutReserve.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/(header&footer)/reserve/_components/PaymentAmount.tsx
  src/app/(header&footer)/reserve/_components/PaymentMethod.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(header&footer)/reserve/_components/TermsAgreement.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/_components/Input/CommonInput.tsx
  src/app/_constants/inputValidate.ts
Labels: 🌻 기타수정사항

#238 [#232] : 마이페이지 예약 상세 api 수정사항 반영 완료
  src/app/(header&footer)/reserve/_components/AddOption.tsx
  src/app/(header&footer)/reserve/_components/PaymentAmount.tsx
  src/app/(header&footer)/reserve/_components/PaymentSubmit.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(mypage)/profile/_components/PaymentAmountForDetail.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/_data/reserve/postReservationDetail.tsx
  src/app/_slices/totalPrice.ts
  src/app/_store/store.ts
  src/app/_utils/switchPayMethod.ts
Labels: 🚀 기능 구현

#239 fix: 마이페이지 디자인 QA 반영
  public/svgs/index.ts
  public/svgs/minus-non.svg
  src/app/(header&footer)/reserve/_components/InfoAboutBookingPerson.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutReserve.tsx
  src/app/(header&footer)/reserve/_components/PaymentAmount.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(mypage)/profile/_components/ImageUpload.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/(mypage)/profile/_components/ReserveItem.tsx
  src/app/(mypage)/profile/_components/ReserveList.tsx
  src/app/(mypage)/profile/_components/ReserveStateLists.tsx
  src/app/(mypage)/profile/_components/Score.tsx
  src/app/(mypage)/profile/_components/Survey.tsx
  src/app/(mypage)/profile/_components/WriteReview.tsx
  src/app/(mypage)/profile/_components/WriteReviewModal.tsx
  src/app/(mypage)/profile/layout.tsx
Labels: 🐞 버그, 🌻 기타수정사항

#243 [#242] : 예약 요청 및 상세 페이지 총 금액 오류 해결
  src/app/(header&footer)/reserve/_components/PaymentAmount.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(mypage)/profile/_components/PaymentAmountForDetail.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
Labels: 🐞 버그

#248 [#245] : 마이 페이지 예약 관련 기능 구현
  package-lock.json
  package.json
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/(mypage)/profile/_components/CancleReserverModal.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/(mypage)/profile/_components/ReserveItem.tsx
  src/app/(mypage)/profile/reserveList/[id]/page.tsx
  src/app/(mypage)/profile/reserveList/page.tsx
  src/app/_constants/reserveList.ts
  src/app/_data/profile/deleteReserve.ts
  src/app/layout.tsx
Labels: 🚀 기능 구현

#241 [#228] 로그인/회원가입 디자인 QA 수정 (LoginForm 에러메시지 문구 변경 필요)
  public/logo/campro.png
  src/app/(sign)/signin/page.tsx
  src/app/(sign)/signup/page.tsx
  src/app/_components/Button/HookFormButton.tsx
  src/app/_components/Form/CommonForm.tsx
  src/app/_components/Form/LoginForm.tsx
  src/app/_components/Form/SignUpForm.tsx
  src/app/_components/Input/AboutInput/ErrorMessage.tsx
  src/app/_components/Input/CommonInput.tsx
  src/app/_constants/inputValidate.ts
  src/app/_data/sign/signin.ts
  src/app/globals.css
Labels: 🐞 버그, 🌻 기타수정사항

#247 [#221] 온보딩 API DB와 연동
  public/data/onboardingMockData.json
  public/svgs/arrowLeft-circle.svg
  public/svgs/arrowRight-circle.svg
  public/svgs/index.ts
  src/app/(onboarding)/_components/OnboardingItem.tsx
  src/app/(onboarding)/_components/OnboardingList.tsx
  src/app/(onboarding)/onboard/question/page.tsx
  src/app/_components/Pagination.tsx
  src/app/_data/onboarding/onboarding.ts
Labels: 🚀 기능 구현

#250 [#211] fix: 검색페이지 Q/A 수정
  package-lock.json
  package.json
  public/svgs/ArrowLeft.svg
  public/svgs/ArrowLeftGray.svg
  public/svgs/arrowDown.svg
  public/svgs/arrowLeft-non.svg
  public/svgs/arrowRight-non.svg
  public/svgs/arrowTest.svg
  public/svgs/arrowUp.svg
  public/svgs/call.svg
  public/svgs/copy.svg
  public/svgs/filter.svg
  public/svgs/location.svg
  public/svgs/markerClustererLarge.svg
  public/svgs/markerClustererSmall.svg
  public/svgs/navigationDown.svg
  public/svgs/navigationLeft.svg
  public/svgs/navigationRight.svg
  public/svgs/navigationUp.svg
  public/svgs/people.svg
  public/svgs/reset.svg
  public/svgs/right.svg
  public/svgs/searchHalf.svg
  public/svgs/searchList.svg
  public/svgs/searchMap.svg
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/reserve/[campId]/[siteId]/page.tsx
  src/app/(header&footer)/reserve/_components/PaymentSubmit.tsx
  src/app/(header)/search/_components/CampSearchList.tsx
  src/app/(header)/search/_components/DetailPanel.tsx
  src/app/(header)/search/_components/KakaoMap.tsx
  src/app/(header)/search/_components/SearchFilter.tsx
  src/app/(header)/search/_components/SortDropdown.tsx
  src/app/(header)/search/page.tsx
  src/app/(mypage)/profile/_components/ImageUpload.tsx
  src/app/(mypage)/profile/_components/PaymentAmountForDetail.tsx
  src/app/(mypage)/profile/_components/ProfileHeader.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/(onboarding)/_components/OnboardingHeader.tsx
  src/app/_components/Button/MapFloatingButton.tsx
  src/app/_components/Dropdown/Selectable.tsx
  src/app/_components/Dropdown/_components/PriceInput.tsx
  src/app/_components/Dropdown/_components/PriceTable.tsx
  src/app/_components/Dropdown/_components/SelectList.tsx
  src/app/_components/Input/LocationInputView.tsx
  src/app/_components/SearchBar/SearchBarForSearch.tsx
  src/app/_constants/detail.ts
  src/app/_constants/mapOptions.tsx
  src/app/_utils/styleSetting.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 🚀 기능 구현, 🐞 버그, 🌻 기타수정사항

#222 [#217] 상세페이지 디자인 QA
  public/svgs/airConditional.svg
  public/svgs/bbq.svg
  public/svgs/bed.svg
  public/svgs/cooking.svg
  public/svgs/electricity.svg
  public/svgs/exercise.svg
  public/svgs/heating.svg
  public/svgs/personalShower.svg
  public/svgs/personalToilet.svg
  public/svgs/play.svg
  public/svgs/publicToilet.svg
  public/svgs/rental.svg
  public/svgs/shower.svg
  public/svgs/sink.svg
  public/svgs/store.svg
  public/svgs/trampoline.svg
  public/svgs/tv.svg
  public/svgs/walkingPath.svg
  public/svgs/waterPlay.svg
  public/svgs/wifi.svg
  src/app/(header&footer)/_components/CampImage/CampImageCarousel.tsx
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/_components/CampImage/Modal/CampImageForModal.tsx
  src/app/(header&footer)/_components/CampImage/Modal/ModalForMobileCampImg.tsx
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/_components/CampPlaceList.tsx
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/AnchorMenu.tsx
  src/app/(header&footer)/overview/_components/CampSiteBasicInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteBookingInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteDetail.tsx
  src/app/(header&footer)/overview/_components/CampSiteFacilities.tsx
  src/app/(header&footer)/overview/_components/CampSiteItem.tsx
  src/app/(header&footer)/overview/_components/CampSiteMap.tsx
  src/app/(header&footer)/overview/_components/CustomerReviews.tsx
  src/app/(header&footer)/overview/_components/ReservationInfo.tsx
  src/app/(header&footer)/overview/_components/ReviewItem.tsx
  src/app/(header&footer)/overview/_components/SiteInfoList.tsx
  src/app/(header&footer)/overview/_components/UsageGuidelines.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/(header&footer)/reserve/_components/TermsAgreement.tsx
  src/app/(header)/search/_components/CampSearchList.tsx
  src/app/(mypage)/profile/_components/ReserveList.tsx
  src/app/(mypage)/profile/_components/SideLists.tsx
  src/app/(onboarding)/_components/OnboardingHeader.tsx
  src/app/(onboarding)/onboard/page.tsx
  src/app/_components/DatePicker/CustomHeaderForDatePicker.tsx
  src/app/_components/Dropdown/_components/SelectList.tsx
  src/app/_components/Header/_components/HeaderModal.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_constants/facilities.tsx
  src/app/_constants/links.tsx
  src/app/api/camping-zone/site/reservation/route.ts
  src/app/api/owner/[ownerId]/reservation/[reserveId]/route.ts
  src/app/api/owner/camping-zone-site/register/route.ts
  src/app/api/owner/reservation-confirm/accept/[reserveId]/route.ts
  src/app/api/owner/reservation-confirm/cancel/[reserveId]/route.ts
  tailwind.config.ts
Labels: 🐞 버그

#261 [#259] 메인페이지, 온보딩 디자인 수정사항 반영 및 로고 추가
  public/logo/campro.png
  public/logo/campro_symbol.png
  public/svgs/coloredHeart.svg
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/overview/_components/CampSiteItem.tsx
  src/app/(header&footer)/overview/_components/TagList.tsx
  src/app/(onboarding)/_components/OnboardingHeader.tsx
  src/app/(onboarding)/_components/OnboardingList.tsx
  src/app/(onboarding)/onboard/page.tsx
  src/app/_components/CategoryItem.tsx
  src/app/_components/CategoryList.tsx
  src/app/_components/Header/index.tsx
  src/app/favicon.ico
  tailwind.config.ts
Labels: 🌻 기타수정사항

#265 [#262] 프로그레스바, 모바일 지도
  public/svgs/index.ts
  public/svgs/people-fill.svg
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/overview/_components/CampSiteFacilities.tsx
  src/app/(header)/search/_components/MapSizeButtons.tsx
  src/app/(header)/search/page.tsx
  src/app/(onboarding)/_components/OnboardingHeader.tsx
  src/app/(onboarding)/_components/OnboardingList.tsx
  src/app/_components/Header/_components/HeaderDropdown.tsx
  src/app/globals.css
Labels: 🌻 기타수정사항

#264 [#211] fix:지도페이지 상세필터
  src/app/(header)/search/_components/DetailPanel.tsx
  src/app/(header)/search/page.tsx
  src/app/_components/Dropdown/Selectable.tsx
  src/app/_components/Dropdown/_components/PriceInput.tsx
Labels: 🐞 버그

#267 [#255] feat : 로그인 후 리다이렉트 기능 구현
  src/app/(header&footer)/overview/_components/ReservationInfo.tsx
  src/app/(header&footer)/reserve/_components/InfoAboutBookingPerson.tsx
  src/app/(onboarding)/onboard/page.tsx
  src/app/_components/Form/LoginForm.tsx
  src/app/_components/Header/_components/HeaderDropdown.tsx
  src/app/_components/Header/_components/HeaderModal.tsx
  src/app/_components/Hero/index.tsx
  src/app/_data/sign/signin.ts
  src/app/_slices/isLogin.ts
  src/app/_slices/redirectUrl.ts
  src/app/_store/store.ts
  src/app/_styles/datePicker.css
Labels: 🚀 기능 구현

#270 [#268] : 예약 요청/마이 페이지 디자인QA 반영
  public/webp/noImage.webp
  src/app/(header&footer)/reserve/[campId]/[siteId]/page.tsx
  src/app/(header&footer)/reserve/_components/SiteInfo.tsx
  src/app/_components/Image/CustomImage.tsx
  src/app/globals.css
Labels: 🌻 기타수정사항

#280 [#278] fix: 검색페이지 api 펫 설정
  src/app/api/camping-zone/list/route.ts
Labels: 🐞 버그, 🌻 기타수정사항

#283 [#282] fix: 사장님 등록페이지 max-people 추가
  src/app/api/owner/camping-zone-site/register/route.ts
Labels: 🐞 버그, 🌻 기타수정사항

#287 [#281] refactor: 캠핑장 등록 API tour data 필드 추가
  src/app/(owner)/_components/OwnerAddTour.tsx
  src/app/(owner)/_constants/ownerInputMapData.ts
  src/app/(owner)/owner/registration/location/page.tsx
  src/app/(owner)/owner/site-registration/page.tsx
  src/app/_data/owner/postCampingZoneRegistration.ts
  src/app/_data/owner/postSiteRegistration.ts
  src/app/api/owner/camping-zone-site/register/route.ts
  src/app/api/owner/camping-zone/register/route.ts
Labels: 🔨 리팩토링

#289 #276: 메인페이지 api 추가내용 반영(임시)
  src/app/(header&footer)/_components/CampPlaceItem.tsx
  src/app/(header&footer)/_components/CampPlaceList.tsx
  src/app/(header&footer)/_components/CampPlaceSection.tsx
  src/app/(header&footer)/page.tsx
  src/app/(mypage)/profile/_components/ReserveItem.tsx
  src/app/_data/main/campList.ts
  src/app/api/camping-zone/main-list/route.ts
Labels: 🌻 기타수정사항

#295 [#294] 메인 카테고리 아이콘 변경
  src/app/_constants/links.tsx
Labels: 🌻 기타수정사항

#298 [#298] 오토캠핑 아이콘 색상수정
  public/svgs/autoCamping.svg
Labels: 🌻 기타수정사항

#300 [#299] fix: 캠핑장 등록 카테고리 버튼 이미지 안나오는 문제
  src/app/(owner)/_constants/ownerCampingCategories.tsx
Labels: 🐞 버그

#302 [#301] fix: 캠핑장 등록 이미지 증식되는 문제
  src/app/(owner)/_components/ImageUploader.tsx
Labels: 🐞 버그

#305 [#296] : 메인 페이지 api 추가사항 반영
  src/app/(header&footer)/_components/CampPlaceList.tsx
  src/app/(header&footer)/_components/CampPlaceSection.tsx
  src/app/(header&footer)/page.tsx
  src/app/api/camping-zone/main-list/route.ts
  src/app/api/user/[userId]/route.ts
Labels: 🌻 기타수정사항

#304 [#303] fix: 캠핑장 상세 안들어가지는 문제
  src/app/_data/owner/postCampingZoneRegistration.ts
  src/app/api/owner/camping-zone/register/route.ts
Labels: 🐞 버그

#308 [#306] 상세페이지 데이터 바인딩
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/CampSiteBasicInfo.tsx
  src/app/(header&footer)/overview/_components/CampSiteDetail.tsx
  src/app/(header&footer)/overview/_components/CampSiteFacilities.tsx
  src/app/(header&footer)/overview/_components/ReservationInfo.tsx
  src/app/(header&footer)/overview/_components/ReviewItem.tsx
  src/app/(header&footer)/overview/_components/UsageGuidelines.tsx
  src/app/_components/SearchBar/SearchBarForOverview.tsx
  src/app/_constants/defaultGuide.ts
  src/app/api/camping-zone/[campingZoneId]/route.ts
Labels: 🌻 기타수정사항

#309 #307: 배치도 이미지 수정
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/(header&footer)/overview/_components/CampSiteMap.tsx
  src/app/(header&footer)/reserve/_components/AddOption.tsx
  src/app/(header&footer)/reserve/_components/ModalForPlanImage.tsx
  src/app/_data/sign/getUserInfo.ts
Labels: 🌻 기타수정사항

#313 [#312] chore: footer style 수정
  src/app/_components/Footer/index.tsx
  src/app/_components/Header/_components/HeaderDropdown.tsx
  src/app/_data/sign/signin.ts
Labels: 🌻 기타수정사항

#311 [#310] 메인 아이콘 사이즈 수정
  src/app/(header&footer)/overview/[id]/page.tsx
  src/app/_constants/links.tsx
Labels: 🌻 기타수정사항

#315 [#314] 캠핑장 사이트를 두번 불러오는현상 수정
  src/app/(header&footer)/overview/_components/CustomerReviews.tsx
  src/app/api/camping-zone/[campingZoneId]/route.ts
Labels: 🐞 버그

#319 [#318] fix: 메인 아이콘 수정
  public/svgs/autoCamping.svg
  public/svgs/chabak.svg
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/_constants/links.tsx
Labels: 🌻 기타수정사항

#321 [#320] fix: 이미지 크기 수정, 최적화
  makeReservation.js
  next.config.mjs
  src/app/(header&footer)/_components/CampImage/CampImageForDesktop.tsx
  src/app/(header&footer)/reserve/[campId]/[siteId]/page.tsx
  src/app/(mypage)/profile/_components/CancleReserverModal.tsx
  src/app/(mypage)/profile/_components/ReserveInfo.tsx
  src/app/(owner)/_components/OwnerModal/OwnerModalContent.tsx
  src/app/(owner)/owner/registration/reservation-guide/page.tsx
  src/app/(test)/test/page.tsx
  src/app/_utils/createMapPosition.ts
  src/app/api/camping-zone/main-list/route.ts
Labels: 🌻 기타수정사항
